# Generated by Django 5.1.3 on 2024-12-16 15:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flashcards", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="Flashcard",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Date of creation"
            ),
        ),
        migrations.AddField(
            model_name="Flashcard",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Date of update"),
        ),
        migrations.AlterField(
            model_name="Flashcard",
            name="category",
            field=models.CharField(
                help_text="category flashcards", max_length=200, verbose_name="category"
            ),
        ),
        migrations.AlterField(
            model_name="Flashcard",
            name="answer",
            field=models.TextField(verbose_name="Answer"),
        ),
        migrations.AlterField(
            model_name="Flashcard",
            name="question",
            field=models.TextField(verbose_name="question"),
        ),
        migrations.AlterField(
            model_name="Flashcard",
            name="source",
            field=models.CharField(
                blank=True,
                help_text="source informacji",
                max_length=200,
                verbose_name="source",
            ),
        ),
    ]
