# Generated by Django 5.1.3 on 2025-01-12 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0003_fiszka_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcard',
            name='correct_answers',
            field=models.IntegerField(default=0, verbose_name='Correct answers'),
        ),
        migrations.AddField(
            model_name='flashcard',
            name='incorrect_answers',
            field=models.IntegerField(default=0, verbose_name='Incorrect answers'),
        ),
        migrations.AlterField(
            model_name='flashcard',
            name='category',
            field=models.CharField(blank=True, max_length=200, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='flashcard',
            name='question',
            field=models.TextField(verbose_name='Question'),
        ),
        migrations.AlterField(
            model_name='flashcard',
            name='source',
            field=models.CharField(blank=True, max_length=200, verbose_name='Source'),
        ),
        migrations.AlterField(
            model_name='flashcard',
            name='state',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20, verbose_name='State'),
        ),
    ]
