# Generated by Django 5.1.3 on 2025-01-13 23:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0005_flashcard_ease_factor_flashcard_interval_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flashcard',
            name='ease_factor',
            field=models.FloatField(default=2.5, verbose_name='Ease Factor'),
        ),
        migrations.AlterField(
            model_name='flashcard',
            name='interval',
            field=models.IntegerField(default=1, verbose_name='Review Interval (days)'),
        ),
        migrations.AlterField(
            model_name='flashcard',
            name='next_review',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Next Review Date'),
        ),
        migrations.AlterField(
            model_name='flashcard',
            name='repetition',
            field=models.IntegerField(default=0, verbose_name='Repetition Count'),
        ),
    ]
