# Generated by Django 5.1.3 on 2025-01-14 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0006_alter_flashcard_ease_factor_alter_flashcard_interval_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flashcard',
            name='ease_factor',
        ),
        migrations.RemoveField(
            model_name='flashcard',
            name='interval',
        ),
        migrations.RemoveField(
            model_name='flashcard',
            name='next_review',
        ),
        migrations.RemoveField(
            model_name='flashcard',
            name='repetition',
        ),
    ]
